// Auto generated by utensor-cli

#ifndef __.._MCU_PROGRAM_DEEP_MLP_H
#define __.._MCU_PROGRAM_DEEP_MLP_H
#include "uTensor/core/context.hpp"
void get_deep_mlp_ctx(Context& ctx, Tensor* input_0);
#endif // __.._MCU_PROGRAM_DEEP_MLP_H