// Auto generated by utensor-cli

#ifndef ___USERS_WFU_VJ_TINYML_TINYML_TRAIN_MODELS_2_MODEL_H
#define ___USERS_WFU_VJ_TINYML_TINYML_TRAIN_MODELS_2_MODEL_H
#include "uTensor/core/context.hpp"
void get_model_ctx(Context& ctx, Tensor* input_0);
#endif // ___USERS_WFU_VJ_TINYML_TINYML_TRAIN_MODELS_2_MODEL_H